/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { IntroStyle } from './types';
import { VOICE_PERSONAS } from './src/personas';

export const INTRO_STYLES: IntroStyle[] = VOICE_PERSONAS;

export const CUSTOM_STYLE: IntroStyle = {
  id: 'custom',
  name: 'Make Your Own',
  description: 'Configure your own custom introducer.',
  defaultVoice: 'Puck',
  color: 'white',
  icon: 'plus',
  templateText: "Enter your text here, then describe a style above and click... 'Dramatize' to rewrite it with more emotions",
};

export const SUPPORTED_LANGUAGES = [
  { name: 'Afrikaans (South Africa)', code: 'af-ZA' },
  { name: 'Albanian (Albania)', code: 'sq-AL' },
  { name: 'Amharic (Ethiopia)', code: 'am-ET' },
  { name: 'Arabic (Egypt)', code: 'ar-EG' },
  { name: 'Arabic (World)', code: 'ar-001' },
  { name: 'Armenian (Armenia)', code: 'hy-AM' },
  { name: 'Azerbaijani (Azerbaijan)', code: 'az-AZ' },
  { name: 'Bangla (Bangladesh)', code: 'bn-BD' },
  { name: 'Basque (Spain)', code: 'eu-ES' },
  { name: 'Belarusian (Belarus)', code: 'be-BY' },
  { name: 'Bulgarian (Bulgaria)', code: 'bg-BG' },
  { name: 'Burmese (Myanmar)', code: 'my-MM' },
  { name: 'Catalan (Spain)', code: 'ca-ES' },
  { name: 'Cebuano (Philippines)', code: 'ceb-PH' },
  { name: 'Chinese, Mandarin (China)', code: 'cmn-CN' },
  { name: 'Chinese, Mandarin (Taiwan)', code: 'cmn-tw' },
  { name: 'Croatian (Croatia)', code: 'hr-HR' },
  { name: 'Czech (Czech Republic)', code: 'cs-CZ' },
  { name: 'Danish (Denmark)', code: 'da-DK' },
  { name: 'Dutch (Netherlands)', code: 'nl-NL' },
  { name: 'English (Australia)', code: 'en-AU' },
  { name: 'English (India)', code: 'en-IN' },
  { name: 'English (United Kingdom)', code: 'en-GB' },
  { name: 'English (United States)', code: 'en-US' },
  { name: 'Estonian (Estonia)', code: 'et-EE' },
  { name: 'Filipino (Philippines)', code: 'fil-PH' },
  { name: 'Finnish (Finland)', code: 'fi-FI' },
  { name: 'French (Canada)', code: 'fr-CA' },
  { name: 'French (France)', code: 'fr-FR' },
  { name: 'Galician (Spain)', code: 'gl-ES' },
  { name: 'Georgian (Georgia)', code: 'ka-GE' },
  { name: 'German (Germany)', code: 'de-DE' },
  { name: 'Greek (Greece)', code: 'el-GR' },
  { name: 'Gujarati (India)', code: 'gu-IN' },
  { name: 'Haitian Creole (Haiti)', code: 'ht-HT' },
  { name: 'Hebrew (Israel)', code: 'he-IL' },
  { name: 'Hindi (India)', code: 'hi-IN' },
  { name: 'Hungarian (Hungary)', code: 'hu-HU' },
  { name: 'Icelandic (Iceland)', code: 'is-IS' },
  { name: 'Indonesian (Indonesia)', code: 'id-ID' },
  { name: 'Italian (Italy)', code: 'it-IT' },
  { name: 'Japanese (Japan)', code: 'ja-JP' },
  { name: 'Javanese (Java)', code: 'jv-ID' },
  { name: 'Kannada (India)', code: 'kn-IN' },
  { name: 'Konkani (India)', code: 'kok-IN' },
  { name: 'Korean (South Korea)', code: 'ko-KR' },
  { name: 'Lao (Laos)', code: 'lo-LA' },
  { name: 'Latin (Vatican City)', code: 'la-VA' },
  { name: 'Latvian (Latvia)', code: 'lv-LV' },
  { name: 'Lithuanian (Lithuania)', code: 'lt-LT' },
  { name: 'Luxembourgish (Luxembourg)', code: 'lb-LU' },
  { name: 'Macedonian (North Macedonia)', code: 'mk-MK' },
  { name: 'Maithili (India)', code: 'mai-IN' },
  { name: 'Malagasy (Madagascar)', code: 'mg-MG' },
  { name: 'Malay (Malaysia)', code: 'ms-MY' },
  { name: 'Malayalam (India)', code: 'ml-IN' },
  { name: 'Marathi (India)', code: 'mr-IN' },
  { name: 'Mongolian (Mongolia)', code: 'mn-MN' },
  { name: 'Nepali (Nepal)', code: 'ne-NP' },
  { name: 'Norwegian, Bokmål (Norway)', code: 'nb-NO' },
  { name: 'Norwegian, Nynorsk (Norway)', code: 'nn-NO' },
  { name: 'Odia (India)', code: 'or-IN' },
  { name: 'Pashto (Afghanistan)', code: 'ps-AF' },
  { name: 'Persian (Iran)', code: 'fa-IR' },
  { name: 'Polish (Poland)', code: 'pl-PL' },
  { name: 'Portuguese (Brazil)', code: 'pt-BR' },
  { name: 'Portuguese (Portugal)', code: 'pt-PT' },
  { name: 'Punjabi (India)', code: 'pa-IN' },
  { name: 'Romanian (Romania)', code: 'ro-RO' },
  { name: 'Russian (Russia)', code: 'ru-RU' },
  { name: 'Serbian (Serbia)', code: 'sr-RS' },
  { name: 'Sindhi (India)', code: 'sd-IN' },
  { name: 'Sinhala (Sri Lanka)', code: 'si-LK' },
  { name: 'Slovak (Slovakia)', code: 'sk-SK' },
  { name: 'Slovenian (Slovenia)', code: 'sl-SI' },
  { name: 'Spanish (Latin America)', code: 'es-419' },
  { name: 'Spanish (Mexico)', code: 'es-MX' },
  { name: 'Spanish (Spain)', code: 'es-ES' },
  { name: 'Swahili (Kenya)', code: 'sw-KE' },
  { name: 'Swedish (Sweden)', code: 'sv-SE' },
  { name: 'Tamil (India)', code: 'ta-IN' },
  { name: 'Telugu (India)', code: 'te-IN' },
  { name: 'Thai (Thailand)', code: 'th-TH' },
  { name: 'Turkish (Turkey)', code: 'tr-TR' },
  { name: 'Ukrainian (Ukraine)', code: 'uk-UA' },
  { name: 'Urdu (Pakistan)', code: 'ur-PK' },
  { name: 'Vietnamese (Vietnam)', code: 'vi-VN' },
];